server {
    listen 8081;
    listen [::]:8081;

    server_name 172.28.45.58;

    root /var/www/IT_209_NguyenDangQuang_De02/src;
    index index.html;

    access_log /var/log/nginx/nguyendangquang-cntt1.access.log;
    error_log /var/log/nginx/nguyendangquang-cntt1.error.log;

    location / {
        allow all;
        try_files $uri $uri/ =404;
    }
}
